version: '3.8'

volumes:
  jenkins-volume:
    name: jenkins-volume

  postgre-data:
    name: postgre-data
  
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk17
    restart: always
    volumes:
      - "./jenkins-volume:/home/jenkins_home"
    ports:
      - "8080:8080"
    deploy:
     resources:
      limits:
        cpus: "0.5"
        memory: 500m     
  
  postgre:
    container_name: postgre
    image: postgres:17.0-alpine3.20
    restart: always
    volumes:
      - "./postgre-data:/data/db"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250m
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=usus-sehat

  app:
    container_name: app
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100m
    build:
      context: "./"
      dockerfile: Dockerfile
    image: "usus-sehat"
    restart: always
    depends_on: 
      - postgre
    ports:
      - "443:443"
    env_file:
      - .env
